"""Build what transcription tests hear: generated clips, and a stand-in model that hears them.

Every transcription test needs audio, and ADR-0033 is explicit that the fixture clips are short
WAV files generated by test support code, "not recordings of anyone": audio of a person is
personal data (`C2`) and has no place in a repository. These builders synthesise the two clips the
contract suite uses -- a second of silence and a second of a pure tone -- with the standard
library alone (`struct`, `math`, and `hivemind.llm.transcription`'s own WAV writer), so they are
exact, deterministic and tiny, and split a clip's frames into push-to-talk chunks. The in-process
Whisper adapter needs one more thing to hear them with and no real model to download: a stand-in
model and loader at the adapter's own seam (`hivemind.llm.providers.whisper.ModelLoader`), whose
segments carry the same field names faster-whisper's do, scripted per test.

Fits into the Hive:
    Test infrastructure (codingrules section 14.5), not shipped. Used by the transcription unit
    tests under packages/hivemind/tests/unit/llm and by
    contracts.test_transcription_provider_contract.

Key invariants:
    - Every clip is 16-bit PCM (the width `hivemind.llm.transcription.encode_wav` writes) at
      `SAMPLE_RATE` unless a caller asks otherwise; nothing here reads a file or the network.
    - `make_chunks` splits only on whole frames, so every chunk it returns is a valid AudioChunk.
    - `StandInWhisperModel.hold`, when given, blocks a run on a worker thread until the test sets
      it: a test that uses it must set it before finishing, or the event loop's executor waits.

See Also:
    - docs/adr/0033-transcription-provider-whisper-first.md for the fixture-clip rule.
    - hivemind.llm.transcription.models for AudioClip and AudioChunk.
"""

from __future__ import annotations

import math
import struct
import threading
from collections.abc import Iterable
from dataclasses import dataclass, field
from typing import BinaryIO

from hivemind.llm.providers.whisper import LoadedModel, WhisperConfig
from hivemind.llm.transcription import PCM_SAMPLE_WIDTH_BYTES, AudioChunk, AudioClip

SAMPLE_RATE = 16_000  # Whisper's own native rate, so no clip here needs resampling.
TONE_HZ = 440.0  # Concert A: an obviously synthetic sound, never mistaken for speech.
TONE_AMPLITUDE = 0.3  # Of full scale: loud enough to register, far from clipping.
_FULL_SCALE = 32_767  # The largest positive 16-bit sample.

__all__ = [
    "SAMPLE_RATE",
    "TONE_HZ",
    "StandInInfo",
    "StandInLoader",
    "StandInSegment",
    "StandInWhisperModel",
    "make_chunks",
    "make_silence_clip",
    "make_tone_clip",
    "silence_pcm",
    "tone_pcm",
]


def silence_pcm(seconds: float = 1.0, sample_rate: int = SAMPLE_RATE, channels: int = 1) -> bytes:
    """Return `seconds` of digital silence as 16-bit PCM frames."""
    frames = round(seconds * sample_rate)
    return bytes(frames * channels * PCM_SAMPLE_WIDTH_BYTES)


def tone_pcm(seconds: float = 1.0, sample_rate: int = SAMPLE_RATE) -> bytes:
    """Return `seconds` of a mono `TONE_HZ` sine wave as 16-bit PCM frames."""
    frames = round(seconds * sample_rate)
    peak = TONE_AMPLITUDE * _FULL_SCALE
    samples = (
        round(peak * math.sin(2 * math.pi * TONE_HZ * index / sample_rate))
        for index in range(frames)
    )
    return b"".join(struct.pack("<h", sample) for sample in samples)


def make_silence_clip(seconds: float = 1.0, sample_rate: int = SAMPLE_RATE) -> AudioClip:
    """Build a validated AudioClip of `seconds` of mono silence."""
    return AudioClip.from_pcm(silence_pcm(seconds, sample_rate), sample_rate, 1)


def make_tone_clip(seconds: float = 1.0, sample_rate: int = SAMPLE_RATE) -> AudioClip:
    """Build a validated AudioClip of `seconds` of a mono `TONE_HZ` tone."""
    return AudioClip.from_pcm(tone_pcm(seconds, sample_rate), sample_rate, 1)


def make_chunks(
    pcm: bytes, pieces: int = 4, sample_rate: int = SAMPLE_RATE, channels: int = 1
) -> list[AudioChunk]:
    """Split `pcm` into about `pieces` whole-frame AudioChunks, in order, dropping nothing.

    Args:
        pcm: 16-bit frames to split; its length must be a whole number of frames.
        pieces: How many chunks to aim for; the last one carries any remainder.
        sample_rate: The rate every chunk states.
        channels: The channel count every chunk states.

    Returns:
        The chunks, whose `pcm` fields concatenate back to `pcm` exactly.
    """
    frame_bytes = PCM_SAMPLE_WIDTH_BYTES * channels
    frames = len(pcm) // frame_bytes
    per_chunk = max(-(-frames // pieces), 1) * frame_bytes
    return [
        AudioChunk(pcm=pcm[start : start + per_chunk], sample_rate=sample_rate, channels=channels)
        for start in range(0, len(pcm), per_chunk)
    ]


@dataclass(frozen=True)
class StandInSegment:
    """One scripted segment, with the field names faster-whisper's own segments carry."""

    start: float
    end: float
    text: str
    avg_logprob: float = -0.25


@dataclass(frozen=True)
class StandInInfo:
    """The run info faster-whisper returns beside its segments: the language it used."""

    language: str


@dataclass
class StandInWhisperModel:
    """A model stand-in the Whisper adapter can load: scripted segments, recorded calls.

    `failure`, when set, is raised by every run (as the library would raise it); `hold`, when
    set, parks every run on its worker thread until the test sets the event.
    """

    segments: list[StandInSegment] = field(default_factory=list)
    detected_language: str = "en"
    failure: Exception | None = None
    hold: threading.Event | None = None
    entered: threading.Event = field(default_factory=threading.Event)
    calls: list[tuple[int, str | None]] = field(default_factory=list)

    def transcribe(
        self, audio: BinaryIO, language: str | None
    ) -> tuple[Iterable[StandInSegment], StandInInfo]:
        """Record the call, then fail, hold, or answer the scripted segments lazily."""
        self.calls.append((len(audio.read()), language))
        self.entered.set()
        if self.hold is not None:
            self.hold.wait()
        if self.failure is not None:
            raise self.failure
        return iter(self.segments), StandInInfo(language or self.detected_language)


@dataclass
class StandInLoader:
    """A ModelLoader that hands out one StandInWhisperModel, or fails the way a load can."""

    model: StandInWhisperModel = field(default_factory=StandInWhisperModel)
    missing: str | None = None
    failure: Exception | None = None
    hold: threading.Event | None = None
    loads: int = 0

    def missing_reason(self) -> str | None:
        """Return the scripted "library absent" reason, or None."""
        return self.missing

    def load(self, config: WhisperConfig) -> LoadedModel:
        """Count the load, then hold, fail, or return the stand-in on the CPU at int8."""
        self.loads += 1
        if self.hold is not None:
            self.hold.wait()
        if self.failure is not None:
            raise self.failure
        return LoadedModel(model=self.model, device="cpu", compute_type="int8")
